Clinical-Genomics/clinical_EPPs

EPPs/reception_control.py

In need of error catches, string formatting, comments... Feel free to sanitize. I dont have time at the moment :/   @robinandeer @ingkebil

order form checker

---

EPPs/art_hist.py
EPPs/make_placement_map.py
EPPs/rerun.py

Updated make_placement_map.py --> modifications in art_hist.py --> modifications in rerun.py
**art_hist.py**
hist_dict holds artifact instances instead of artifact.uris, just as in make_art_hist_no_stop().
**rerun.py**
adding a line to convert hist_dict to a hist_dict contining uris
**make_placement_map.py**
Main change: source container can now be either:
- container of input artifact to current process
- container of original artifact
- container of input artifact to other given process
Source container is deficed by the arguments: **--other_source** and **--orig**
Also changing the html for 96 well plate to container both original container name and source container

Updated make_placement_map.py needed modifications in art_hist.py wic

---

EPPs/setQC.py

This will replace set_qc.py when accepted.

new script to set qc

---

EPPs/calculate_amount.py
EPPs/setQC.py

The calculate_amount script needed a major clean up.

Calculate amount

---

EPPs/calc_volumes_nova.py

Script to calculate volumes for NovaSeq Xp and NovaSeq standard

Nova volumes

---

EPPs/denaturate_nova_xp.py

New script to set denaturation volumes for NovaSeq Xp, based on flowcell type.
The script is taylored for the Xp Denature & ExAmp step in the NovaSeq WF.

New script for the Xp Denature & ExAmp step

---

EPPs/copy_field_art2samp.py

new little script to copy fields from art to samp'

new little script to copy fields from art to samp

---

EPPs/calculate_beads.py

New script for new Buffer Exchenge step in microbial workflow. Has been tested.

new script to calculate h2o and beads volume

---

EPPs/96well_placement_map.py

Separating placement map script for 96 well plate, from the general script. Aim to have a separate script for each type of map. To keep it more simple

new placement map

---

EPPs/check_configuration.py

This script would cover all the situations we talked about @ingkebil . Namely answer the questions:
Search all active workflow, protol, step names in all automations and step udfs.
Where is this script used?
In what automations is this value given as argument? (Could be a process name, udf name, workflow name or whatever)
In what steps do we have this value given as process udf optional preset? (Could be a process name, udf name, workflow name or whatever)
Maybe we could have a chat about it later this week? @ingkebil

script to check configurations

---

EPPs/get_average_size_and_set_qc.py

Adding argument for both upper and lower threshold

adding argument for both upper and lower threshold

---

EPPs/MAF_calc_vol.py
EPPs/make_placement_map.py

Specifications in [this](https://github.com/Clinical-Genomics/clinical_EPPs/issues/125) issue

Modifications of  genotype step

---

EPPs/get_missing_reads.py

no exeption for WGS

---

EPPs/make_csv.py

new general script to generate csv file for bravo

---

EPPs/calculations_twist.py

Requested by @annaengstrom Part of issue #128

volume not higher then 15

---

EPPs/MAF_calc_vol.py

Requested by @annaengstrom . solving issue #125

Concentration < 4, not acceptable

---

EPPs/calc_volumes_nova.py
EPPs/denaturate_nova_xp.py

Adding SP workflow to the NovaSeq protocol

New flowcell type SP

---

EPPs/reads_missing_pool.py

This PR solves issue #145 
It sums missing reads for all samples in a pool and populates a new udf on artifact level, called "Missing reads Pool (M)"
The script has been tested on stage by @mayabrandi  and @AnnaZetterlund

new script to set new udf for pools

---

EPPs/calculations_twist.py
EPPs/make_pooling_map.py

This PR adds a treshold on amount taken of input sample to pool. It also shows amount in placement map. Tests were performed on stage.

low amount not accepted

---

EPPs/get_missing_reads.py

This PR changes the rule for min reads of a sample.
Questions:
Are the rules here affected by [this](https://docs.google.com/document/d/1dm1W21EQlrgDpiLKQ-XlEL7lW11U7ASak3cNATRB_6U/edit)?
**How to prepare for test**:
*How to test**:
**Expected test outcome**:
**Review:**

adjustimg rule for target reads

---

EPPs/check_missing_sample_udfs.py

Missed the last commit that was tested in previous PR. Here it comes

miss spelled udf

---

EPPs/check_duplicate_samples.py

This PR adds a new script to check for duplicate samples in step
**How to prepare for test**:
```
cd /home/glsai/opt/clinical_EPPs
pip install -e .
```
**How to test**:
This is a requeue of a step that was loaded with duplicate samples containing different indexes, when run in production in march. 
**Expected test outcome**:
**Review:**

new script to check for duplicate samples in step

---

one_time_scripts/check_config.py

This PR adds a one time check config

one time check_config

---

one_time_scripts/check_config.py

visual printing

---

one_time_scripts/check_config.py

printig stage name

---

EPPs/get_missing_reads.py
EPPs/prepare_new_samples.py
clinical_EPPs/cg_face.py

This PR fixes a depencency fof the old and depricated cgface app. 
**Review:**

making independent of cgface

---

EPPs/check_protocol_nova.py

This PR adds rules for SP flowcells
**Review:**

adding rules for SP

---

EPPs/qPCR_dilution.py

This PR adds/fixes ...
This will hopefully remove the issue that causes single samples to not get data in the qPCR step.
**How to prepare for test**:
```
cd /home/glsai/opt/clinical_EPPs
pip install -e .
```
**How to test**:
**Expected test outcome**:
**Review:**

Patch to deviation #328

---

EPPs/attach_novaseq_xml.py

This PR fixes:
- Patches the expected flow cell run dir path on the lims servers.
**How to prepare for test**:
```
cd /home/glsai/opt/clinical_EPPs
pip install -e .
```
**How to test**:
**Expected test outcome**:
**Review:**

Patch flow cell run directory path
